config/routes.rb
Spree::Core::Engine.routes.draw do
  
  # Add your extension routes here
  
   #match '/tickets/open' => 'Tickets#open'
  match 'support/tickets/login' => 'Support::Tickets#login'
  match 'support/tickets' => 'Support::Tickets#open'
   
  namespace :support do 
    resources :tickets do
      collection do
        get 'open'
        get 'close'
        get 'all'
      end
      member do
        get 'closed'
      end      
    end
  end
  
  
  namespace :admin do 
    resources :tickets do
      collection do
        get 'myopen'
        get 'mynew'
        get 'myclose'
        get 'myall'
        get 'unassigned'
        get 'all'
      end
      member do
        get 'closed'
      end      
    end
  end
  
  # resources :posts, :path => "/support/tickets"
  # resources :tickets, :path => "/support/tickets"
  # scope :module => "aa" do
  #   resources :tickets
  # end
  
end

app/models/ticket.rb
  class Ticket < ActiveRecord::Base
    belongs_to :ticket_category, :class_name => "TicketCategory", :foreign_key => "category_id"
    belongs_to :ticket_state, :class_name => "TicketState", :foreign_key => "state_id"
    has_many :ticket_messages, :class_name => "TicketMessage",  :foreign_key => "ticket_id"
    #has_many :ticket_assignees, :class_name => "TicketAssignee", :foreign_key => "ticket_id"
    belongs_to :user, :class_name => "Spree::User", :foreign_key => "user_id"
    belongs_to :closed_by_user, :class_name => "Spree::User", :foreign_key => "closed_by"
    belongs_to :admin_user, :class_name => "Spree::User", :foreign_key => "admin_user_id"

    accepts_nested_attributes_for :ticket_messages
    # validates :subject, :presence => true
    # validates :state_id, :presence => true
    before_create :generate_ticket_number
    
    
    # scope :open, where("state_id != #{TicketState.id_for_closed}").order('updated_at DESC')
    # scope :close, where("state_id = #{TicketState.id_for_closed}").order('updated_at DESC')

    def self.open_tickets_by_user(user)
      return Ticket.where("state_id != ? and user_id = ?", TicketState.state_closed.id, user.id).order('updated_at DESC')      
    end
    
    def self.closed_tickets_by_user(user)
      return Ticket.where("state_id = ? and user_id = ?", TicketState.state_closed.id, user.id).order('updated_at DESC')      
    end
    
    def self.all_tickets_by_user(user)
      return Ticket.where("user_id = ? and state_id is not null", user.id).order('updated_at DESC')      
    end
        
    private
      def generate_ticket_number
        return self.number unless self.number.blank?
        record = true
        while record
          random = "T#{Array.new(9){rand(8)}.join}"
          record = self.class.where(:number => random).first
        end
        self.number = random
      end
        
  end

app/controllers/spree/admin/tickets_controller.rb
module Spree
  module Admin
    class TicketsController < Spree::Admin::BaseController
      respond_to :html      
      PER_PAGE = 20
      before_filter :load_search_object, :except => [:edit, :new, :update, :create]

      def load_search_object
        params[:search] ||= {}
        params[:search][:meta_sort] ||= 'updated_at.desc'
        @search = Ticket.metasearch(params[:search])        
      end
      
      def index
       if !params[:search][:created_at_greater_than].blank?
          params[:search][:created_at_greater_than] = Time.zone.parse(params[:search][:created_at_greater_than]).beginning_of_day rescue ""
        end

        if !params[:search][:created_at_less_than].blank?
          params[:search][:created_at_less_than] = Time.zone.parse(params[:search][:created_at_less_than]).end_of_day rescue ""
        end


        @collections = Ticket.metasearch(params[:search]).includes([:user, :admin_user, :ticket_state]).page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE)
        respond_with(@collections)        
      end
      
      def all
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"        
      end
      
      def unassigned
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).where("admin_user_id is null").order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"
      end
      
      def myopen
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).where("admin_user_id = ? and state_id != ?", current_user.id, TicketState.state_closed.id).order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"        
      end
      
      def mynew
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).where("admin_user_id = ? and state_id != ? and state_id != ? and state_id != ?", current_user.id, TicketState.state_closed.id, TicketState.state_require_customer_response.id, TicketState.state_resolved.id).order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"        
      end
      

      def myclose
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).where("admin_user_id = ? and state_id = ?", current_user.id, TicketState.state_closed.id).order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"        
      end

      def myall
        @collections = Ticket.includes(:user, :admin_user, :ticket_state).where("admin_user_id = ?", current_user.id).order("updated_at desc").page(params[:page]).per(Spree::Admin::TicketsController::PER_PAGE);
        render "index"        
      end
      
      def edit
        @ticket = Ticket.find_by_number!(params[:id])
        @backend = true
        @message = TicketMessage.new
        admin_role = Spree::Role.find_by_name 'admin'
        @admin_users = admin_role.users
        customer = Spree::User.new
        customer.id = -1
        customer.email = "Cutomer"
        @admin_users.unshift customer                
      end
      
      def update
        @ticket = Ticket.find(params[:id])
        admin_user_id = params[:ticket][:admin_user_id].to_i
        @ticket.state_id = params[:ticket][:state_id].to_i
        message = TicketMessage.new
        message.user_id = current_user.id
        message.message_text =  params[:ticket][:ticket_message][:message_text]
        @ticket.ticket_messages = Array.new if @ticket.ticket_messages.nil?
        message.state_id = params[:ticket][:state_id]
        
        if admin_user_id > 0
            @ticket.admin_user_id = admin_user_id 
            #message.state_id = @ticket.state_id = TicketState.state_ticket_transfered.id                  
        end
        
        if @ticket.state_id == TicketState.state_closed.id
          @ticket.closed_by = current_user.id
          @ticket.closed_at = Time.now
        end
        
        if !@ticket.save
          flash[:error] = "An error occurred. please contact support"
          respond_with(@ticket, :location => edit_admin_ticket_path(@ticket.number))
          return
        end          
        
                  
        if admin_user_id <= 0
          #transfer to customer
            if message.message_text.blank?
              flash[:error] = "Message can not be left blank if sending to customer"
              respond_with(@ticket, :location => edit_admin_ticket_path(@ticket.number))
              return  
            else
              message.transfered_to_user_id = @ticket.user.id
              message.is_visible_to_customer = true
              message.transfered_to_user_id = nil
              #message.is_internal_transfer = false
            end  
        else
            message.is_visible_to_customer = false            
            message.transfered_to_user_id = admin_user_id
            #message.is_internal_transfer = true

        end
        if !(@ticket.ticket_messages.push message)
              flash[:error] = "An error occurred. please contact support"
              respond_with(@ticket, :location => edit_admin_ticket_path(@ticket.number))
              return
        end
        
        if admin_user_id <= 0 && @ticket.state_id == TicketState.state_require_customer_response.id
#          begin
            Spree::TicketMailer.updated_ticket_mail(@ticket.user, @ticket, message).deliver
          # rescue => ex
          #   Rails.logger.info("Can not send ticket opened email: #{ex}")
          # end
        end
        
        flash.notice = "This Ticket has been updated!"
        respond_with(@ticket, :location => edit_admin_ticket_path(@ticket.number))
          
        
      end
      
      def new
        @object = Ticket.new
        @object.ticket_messages = Array.new.push(TicketMessage.new)
        admin_role = Spree::Role.find_by_name 'admin'
        @admin_users = admin_role.users
      end
  
      def create        
      @object = Ticket.new
      @object.user = current_user
      @object.state_id = TicketState.state_new.id
      
      params[:ticket][:ticket_messages_attributes]["0"][:state_id] = @object.state_id
      params[:ticket][:ticket_messages_attributes]["0"][:user_id] = current_user.id
      params[:ticket][:ticket_messages_attributes]["0"][:transfered_to_user_id] = params[:ticket][:admin_user_id]
       
     if @object.update_attributes(params[:ticket])
        begin
          Spree::TicketMailer.new_ticket_mail(@object.user, @object).deliver
        rescue => ex
          Rails.logger.info("Can not send ticket opened email: #{ex}")
        end
        redirect_to :action => :myopen
      else
        flash[:error] = "An error occurred please contact the support"
        redirect_to :action => :new
      end     
    end

      
      # def update
      #  
      # 
      #  message = TicketMessage.new
      #  message.message_text =  params[:ticket][:ticket_message][:message_text]
      #  @ticket.ticket_messages = Array.new if @ticket.ticket_messages.nil?
      #  @ticket.ticket_messages.is_internal_transfer
      #  @ticket.ticket_messages.push message
      #   
      #   end
      #   if @ticket.save
      #     flash.notice = "Thank you. Your ticket has been updated we will respond shortly." if !params[:ticket].blank? && !params[:ticket][:ticket_message].blank? && !params[:ticket][:ticket_message][:message_text].blank?
      #   end        
      #   respond_with(@ticket, :location => admin_ticket_path(@ticket.number))
      # end      
      
    end
  end
end

app/controllers/spree/support/tickets_controller.rb
module Spree
  module Support
    class TicketsController < Spree::ContentController
      respond_to :html
      before_filter :page_title
      before_filter :check_authorization, :except => [:login]

      
      def login        
      end
      
      
      
      def page_title
        @page_title  = 'Support'
      end
      
      def open
        @current_page = "View Open"
        @tickets = Ticket.open_tickets_by_user(current_user)
        @type = "open"
        render "index"
      end
      
      def close
        @current_page = "View Closed"
        @tickets = Ticket.closed_tickets_by_user(current_user)
        @type = "closed"        
        render "index"
      end
      
      def all
        @current_page = "View All"
        @tickets = Ticket.all_tickets_by_user(current_user)
        @type = ""
        render "index"        
      end
      
      def show
        @ticket = Ticket.find_by_number!(params[:id])
        @backend = false
        @message = TicketMessage.new
      end
      
      def closed
        @ticket = Ticket.find_by_number!(params[:id])
        @ticket.ticket_state = TicketState.state_closed
        @ticket.closed_by = current_user.id
        @ticket.closed_at = Time.now
        if @ticket.save
          redirect_to :action => :open
        else
          flash.error = "Sorry there is a problem. Please contact our support@betterbequick.com.au if problem continues."
          respond_with(@ticket, :location => support_ticket_path(@ticket.number))
        end
      end
      
      def new
        @current_page = "New Ticket"
        @object = Ticket.new
        @object.ticket_messages = Array.new.push(TicketMessage.new)        
      end
      
      def update
        @ticket = Ticket.find(params[:id])
        @ticket.ticket_state = TicketState.state_customer_responsed
        if !params[:ticket].blank? && !params[:ticket][:ticket_message].blank? && !params[:ticket][:ticket_message][:message_text].blank?
           message = TicketMessage.new
           message.message_text =  params[:ticket][:ticket_message][:message_text]
           message.state_id = @ticket.state_id
           message.user_id = @ticket.user_id
           @ticket.ticket_messages = Array.new if @ticket.ticket_messages.nil?           
           @ticket.ticket_messages.push message           
        end
        if @ticket.save
          flash.notice = "Thank you. Your ticket has been updated we will respond shortly." if !params[:ticket].blank? && !params[:ticket][:ticket_message].blank? && !params[:ticket][:ticket_message][:message_text].blank?
        end        
        respond_with(@ticket, :location => support_ticket_path(@ticket.number))
      end
      
      def create        
        @object = Ticket.new
        @object.user = current_user
        @object.state_id = TicketState.state_new.id
        
        params[:ticket][:ticket_messages_attributes]["0"][:state_id] = @object.state_id
        params[:ticket][:ticket_messages_attributes]["0"][:user_id] = current_user.id
         
       if @object.update_attributes(params[:ticket])
          begin
            Spree::TicketMailer.new_ticket_mail(@object.user, @object).deliver
          rescue => ex
            Rails.logger.info("Can not send ticket opened email: #{ex}")
          end
          redirect_to :action => :open
        else
          flash[:error] = "Sorry there is a problem. Please contact our support@betterbequick.com.au if problem continues."
          redirect_to :action => :new
        end     
      end
      
      private
        def check_authorization
          return if current_user
          store_location
          #redirect_to spree.login_path and return
          redirect_to :action => :login
          return          
        end

    end
  end
end

app/helpers/spree/admin/tickets_helper.rb
module Spree
  module Admin

    module TicketsHelper
    end
  end
end

app/helpers/spree/support/tickets_helper.rb
module Spree
  module Support
    module TicketsHelper
      
      # def support_ticket_path(ticket)
      #   return "/support/tickets/new"
      # end
      def message_color(user, is_internal_transfer)
        if is_internal_transfer
          return "ticket-message-transfer"
        end
        if user.admin_user?
          return "ticket-message-admin-color"
        else
          return "ticket-message-customer-color"
        end
      end
      
      def hind_faq(category, first_id)
        return "" if category.id == first_id
        return "hidden"
      end
              
      def message_title(user)
        if !user.admin_user?
          return "Customer said:"
        else
          return "Better Be Quicker Customer Service said:"
        end        
      end
      
      def avialbe_categories
        return TicketCategory.all
      end
      
      def current_page(link_title)
        #Rails.logger.info("PAGE TITLE=========================#{@current_page}===========#{link_title}")
        if @current_page == link_title
          return "class='active'"          
        end
        return ""
      end
      
      def new_aa_ticket_path
        return "/support/tickets/new"
      end
      
      def tickets_sum(amount, type)
        if amount == 1
          return "You have 1 #{type} ticket"
        else
          return "You have #{amount} #{type} tickets"
        end
      end
      
    end
  end
end

app/helpers/spree/tickets_helper.rb
module Spree
  #module Support
    module TicketsHelper
      
      # def support_ticket_path(ticket)
      #   return "/support/tickets/new"
      # end
      def message_color(user, is_internal_transfer)
        if is_internal_transfer
          return "ticket-message-transfer"
        end
        if user.admin_user?
          return "ticket-message-admin-color"
        else
          return "ticket-message-customer-color"
        end
      end
      
      def hind_faq(category, first_id)
        return "" if category.id == first_id
        return "hidden"
      end
              
      def message_title(user)
        if !user.admin_user?
          return "Customer said:"
        else
          return "Better Be Quicker Customer Service said:"
        end        
      end
      
      def avialbe_categories
        return TicketCategory.all
      end
      
      def current_page(link_title)
        #Rails.logger.info("PAGE TITLE=========================#{@current_page}===========#{link_title}")
        if @current_page == link_title
          return "class='active'"          
        end
        return ""
      end
      
      def new_aa_ticket_path
        return "/support/tickets/new"
      end
      
      def tickets_sum(amount, type)
        if amount == 1
          return "You have 1 #{type} ticket"
        else
          return "You have #{amount} #{type} tickets"
        end
      end
      
    end
  #end
end

app/views/spree/tickets/share/_form.html.erb
<%= javascript_tag do -%>
  (function($){
    $(document).ready(function(){
      $("#ticket_category_id").bind("change", function() {
        $(".ticket_faq").addClass("hidden")
        $("#category" + $(this).attr('value')).removeClass("hidden").show("slow");
      });    
      if($('#new_ticket').is('*')){
        $('#new_ticket').validate({
          highlight: function(element, errorClass) {
               $(element).parents(".control-group").addClass("error")
          },          
          errorClass: "help-inline"
        });
      }
    });
  })(jQuery);
  
  function toggleAnswer(i) {
    $('#faq-answer' + i).toggle('slow');
    return false;
  }
<% end -%>



<div class="inner">

      <p class="control-group string required">
        <%= f.label :category_id, raw('<abbr title="required">*</abbr> ') + t(:category), :class => "string required control-label" %>
        <span class="controls">
          <%= f.collection_select :category_id, TicketCategory.all, :id, :name, {:selected=>TicketCategory.first.id}, {:class => 'required string valid wide-field'} %>
        </span>
      </p>
      
      <p>            
        <% TicketCategory.all.each do |category| -%>          
          <div class="ticket_faq <%=hind_faq(category, TicketCategory.first.id)%>" id="category<%=category.id%>">
              <% if category.ticket_faqs.size > 0 %>
                <div class="faq_summery">Here are some popular '<%=category.name%>' Questions:</div>
                <ul class="nav nav-pills nav-stacked">
                  <%category.ticket_faqs.each do |faq|%>
                    <li>
                      <a href="#" onclick="toggleAnswer(<%=faq.id%>);return false">&bull;&nbsp;<span><%=faq.question.html_safe%></span></a>
                      <div class="ticket_answer hidden" id="faq-answer<%=faq.id%>"><%=faq.answer.html_safe%></div>
                    </li>
                  <%end%>
                </ul>
              <% end %>
              <div class="ticket_hint"><%=category.hint_text%></div>
          </div>          
        <% end -%>
      </p>
  
      <p class="control-group string required">
        <%= f.label :subject, raw('<abbr title="required">*</abbr> ') + t(:subject), :class => "string required control-label" %>
        <span  class="controls">
          <%= f.text_field :subject, :class => 'required string valid wide-field' %>
        </span>
      </p>
      
      <%= f.fields_for :ticket_messages do |messages_form| %>
        <p class="control-group string required">
          <%= messages_form.input :message_text,  :as => :text, :input_html => { :cols => "", :rows => 6, :class => "required string valid" } %>
        </p>
      
      <% end %>  
  
</div>

  <div class="form-actions" data-hook="buttons">
    <%= button_tag :class => 'btn btn-success btn-large' do t(:create) end %>
  </div>

  <br/>

app/views/spree/tickets/share/_form_backend.html.erb
<div class="inner">

      <p class="control-group string">
        <%= f.label :category_id, t(:category) %><br/>
        <span class="controls">
          <%= f.collection_select :category_id, TicketCategory.all, :id, :name, {:selected=>TicketCategory.first.id} %>
        </span>
      </p>
      
      <p class="control-group string">
        <%= f.label :admin_user_id, t(:assign_to) %><br/>
        <span class="controls">
          <%= f.collection_select :admin_user_id, @admin_users, :id, :email, {} %>
        </span>
      </p>
  
      <p class="control-group string">
        <%= f.label :subject, t(:subject) %><br/>
        <span  class="controls">
          <%= f.text_field :subject %>
        </span>
      </p>

      
      <%= f.fields_for :ticket_messages do |messages_form| %>
        <p class="control-group string">
          <%= messages_form.input :message_text,  :as => :text, :input_html => { :cols => "", :rows => 6, :class => "string valid" } %>
        </p>
      
      <% end %>  
  
</div>

  <div class="form-actions" data-hook="buttons">
    <p><%= button "Create" %></p>
  </div>

  <br/>

app/views/spree/tickets/share/_message_form.html.erb
      <%= f.fields_for @message do |messages_form| %>
        <p class="control-group string required">
          <%= messages_form.input :message_text,  :label => "Comments:", :as => :text, :input_html => { :cols => "", :rows => 6, :class => "required string valid" } %>
        </p>
      
      <% end %>  

app/views/spree/tickets/share/_ticket_backend.html.erb
<div class="ticket-detail">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @ticket } %>
  
  Ticket #<%=@ticket.number%>
  <br/><br/>
  Customer: <b><%=@ticket.user.email%></b>
  <br/><br/>
  <%=link_to t(:view_all_customer_tickets), admin_tickets_path + "?search[user_email_like]=#{@ticket.user.email}"%>
  <br/><br/>
  <%=link_to t(:view_all_customer_orders), admin_orders_path + "?search[user_email_like]=#{@ticket.user.email}&search[completed_at_is_not_null]=1"%>  
  <br/><br/>
  Assigned to: <b><%=@ticket.admin_user.email if !@ticket.admin_user.nil?%></b>
  <br/><br/>  
  Category: <%=@ticket.ticket_category.name%>
  <br/><br/>  
  Subject: <%=@ticket.subject%>
  <br/><br/>
  Status: <%=@ticket.ticket_state.name%>
  <br/><br/>
  Closed by: <%=@ticket.closed_by_user.email if @ticket.closed_by_user%>
  <br/><br/>
  Closed at: <%=@ticket.closed_at%>
  <br/><br/>
  
  
  
  <% @ticket.ticket_messages.each do |message| %>
    <% if message.is_visible_to_customer || @backend%>
      <%= render :partial => "spree/tickets/share/ticket_message_body", :locals => { :message => message, :backend => true } %>
    <% end %>
  <% end %>
  
    
    <div class="message_form">
    <%= simple_form_for [:admin,@ticket], :html => { :multipart => true, :id=> "edit_ticket"} do |f| %>
    <fieldset data-hook="new_<%=@object.class.name%>">
      <br />
      <%= render :partial => "spree/tickets/share/message_form", :locals => { :f => f } %>

<br /><br /><br />
       <p>if you want to make a note please transfer to self</p>
      <p class="control-group string">
        <%= f.label :admin_user_id, t(:send_to), :class => "text optional control-label" %>
        <span class="controls">
          <%= f.collection_select :admin_user_id, @admin_users, :id, :email,  {} %>
        </span>
      </p>

      <p class="control-group string">
        <%= f.label :state_id, t(:state), :class => "text optional control-label" %>
        <span class="controls">
          <%= f.collection_select :state_id, TicketState.all, :id, :name, {} %>
        </span>
      </p>

      
      <div>
        <div class="form-actions" data-hook="buttons">
          <p><%= button "Update" %></p>
        </div>
      </div>
        
    </fieldset> 
 
    </div>
    </p>        
  
    
  <%end%>
  
</div>

app/views/spree/tickets/share/_ticket_frontend.html.erb
<%= javascript_tag do -%>
  (function($){
    $(document).ready(function(){
      if($('#edit_ticket').is('*')){
        $('#edit_ticket').validate({
          highlight: function(element, errorClass) {
               $(element).parents(".control-group").addClass("error")
          },          
          errorClass: "help-inline"
        });
      }
    });
  })(jQuery);
<% end -%>


<div class="ticket-detail">
  <% if flash[:error] %>
    <div class="alert alert-error"><%= flash[:error] %></div>
  <% end %>
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @ticket } %>
  
  Ticket #<%=@ticket.number%>
  <br/><br/>
  Subject: <%=@ticket.subject%>
  <br/><br/>
  Status: <%=@ticket.ticket_state.name%>
  <br/><br/>
  
  
  
  <% @ticket.ticket_messages.each do |message| %>
    <% if message.is_visible_to_customer%>
      <%= render :partial => "spree/tickets/share/ticket_message_body", :locals => { :message => message, :backend => false } %>
    <% end %>
  <% end %>
  
  <%if @ticket.ticket_state.name != TicketState::CLOSED%>
    
    <div class="message_form">
    <%= simple_form_for [:support,@ticket], :html => { :multipart => true, :id=> "edit_ticket"} do |f| %>
    <fieldset data-hook="new_<%=@object.class.name%>">
      <br />
      <%= render :partial => "spree/tickets/share/message_form", :locals => { :f => f } %>
      <div>
        <div class="form-actions" data-hook="buttons">
          <%= button_tag :class => 'btn btn-success btn-large' do t(:update) end %>
        </div>
        <div class="closed-button">
          <%= link_to "Close", closed_support_ticket_path(@ticket.number), :class => 'btn btn-success btn-large' %>
        </div>
      </div>
        
    </fieldset> 
 
    <% end %>
    </div>
    </p>        
  
    
  <%end%>
  
</div>

app/views/spree/tickets/share/_ticket_message_body.html.erb
<div class="ticket-message-body <%=message_color(message.user, message.is_internal_transfer)%>">
  <%if message.is_internal_transfer%>
    <div><p><i>Internally transfered to <%=message.transfered_to_user.email if !message.transfered_to_user.nil?%></i></p></div>
  <%end%>    
  <% if backend %>
    <div><p><i>State: <%=message.ticket_state.name%></i></p></div>
  <% end %>
  <div class="title_wrap">
     <div class="title_wrap_left"><b><%=message_title(message.user)%></b></div>
      <div class="title_wrap_right"><%=message.updated_at%></div>
  </div>
  <div class="clear" ></div><br/>
  <div><p><%=message.message_text%><%=message.admin_signiture%></p></div>
  <%if message.is_visible_to_customer && backend %>
    <div class="customer-visible-icon"><%=image_tag("visible_to_customer.gif")%></div>
  <%end%>
</div>

app/views/spree/tickets/share/_ticket_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav">
    <%= tab :my_new_tickets, :url => mynew_admin_tickets_path, :match_path => '/tickets/mynew' %>
    <%= tab :my_open_tickets, :url => myopen_admin_tickets_path, :match_path => '/tickets/myopen' %>
    <%= tab :my_closed_tickets, :url => myclose_admin_tickets_path, :match_path => '/tickets/myclose' %>
    <%= tab :my_all_tickets, :url => myall_admin_tickets_path, :match_path => '/tickets/myall' %>
    <%= tab :unassigned_tickets, :url => unassigned_admin_tickets_path, :match_path => '/tickets/unassigned' %>
    <%= tab :all_tickets, :url => all_admin_tickets_path, :match_path => '/tickets/all' %>
    <%= tab :create_a_ticket, :url => new_admin_ticket_path, :match_path => '/tickets/new' %>
  </ul>
<% end %>

app/views/spree/tickets/share/_tickets_table.html.erb
<table class="tickets-table table table-hover table-striped">
  <% @tickets.each do |ticket| %>
    <tr>
      <td width="20%"><%=link_to "#" + ticket.number, support_ticket_path(ticket.number)%></td>
      <td width="80%"><b><%=ticket.subject%></b><br/>
          Status: <%=ticket.ticket_state.name%><br/>
          Last Modified: <%=ticket.updated_at%>
      </td>
    </tr>
  <% end %>
</table>